[package]
name = "neosvr-inventory-move"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
chrono = "0.4.19"
clap = { version = "3.2.15", features = ["derive"] }
derive_more = "0.99.17"
email_address = "0.2.1"
fern = { version = "0.6.1", features = ["colored"] }
log = "0.4.17"
once_cell = "1.13.0"
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
tokio = { version = "1.20.1", features = ["full"] }
url = { version = "2.2.2", features = ["serde"] }
